# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

stages:
   - install
   - build
   - test

# NEW
variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - node_modules
# END NEW

# Jobs 

install_dependencies:
  stage: install
  script:
    - npm ci

bundle_app:
  stage: build
  artifacts:
    paths:
      - build/ 
  script:
    - CI=false npm run build

test_jobX:
  stage: test
  only:
    - staging
  script:
    - echo "running cypress tests on staging branch"

e2etest:    
    stage: test
    only:
    - staging
    - develop
    before_script:
      - npm install -g http-server
      - npm install cypress
    script:
       # start the server in the background
      - echo "running cypress tests on staging branch"
      - npm run start:ci